development: &default
  adapter: postgresql
  database: vernewlace_development
  encoding: utf8
  min_messages: warning
  pool: 5
  timeout: 5000
  host: localhost
  port: 5432
  username: postgres
  password: 123412341234
test:
  <<: *default
  database: vernewlace_test
  username: postgres
  password: 123412341234
