development: &default
  adapter: postgresql
<<<<<<< HEAD
  pool: 5
  timeout: 5000
  encoding: utf8
  host: localhost

development:
  <<: *default
  database: vernewlace_development
  username: postgres
  password: 123456

=======
  database: vernewlace_development
  encoding: utf8
  min_messages: warning
  pool: 5
  timeout: 5000
  host: localhost
  port: 5432
  username: postgres
  password: 12341234
>>>>>>> origin
test:
  <<: *default
  database: vernewlace_test
  username: postgres
<<<<<<< HEAD
  password: 123456
=======
  password: 12341234
>>>>>>> origin
